/***********************************************************************/
/*                                                                     */
/*  FILE        :RX62T_lab4.c                                          */
/*  DATE        :Tue, Mar 12, 2013                                     */
/*  DESCRIPTION :Main Program                                          */
/*  CPU TYPE    :RX62T                                                 */
/*                                                                     */
/*  This file is generated by Renesas Project Generator (Ver.4.51).    */
/*  NOTE:THIS IS A TYPICAL EXAMPLE.                                    */
/*                                                                     */
/***********************************************************************/
                  
	
#include "iodefine_RPDL.h"	
#include "math.h"

//#include "typedefine.h"
#ifdef __cplusplus
//#include <ios>                        // Remove the comment when you use ios
//_SINT ios_base::Init::init_cnt;       // Remove the comment when you use ios
#endif


void main(void);
#ifdef __cplusplus
extern "C" {
void abort(void);
}
#endif

///////////////Delay
int q=0;
///////////////Main
int MTU0A=0,MTU0C=0,MTU1A=0,MTU2A=0,MTU3A=0,MTU3C=0,MTU4A=0,MTU4C=0,MTU7A=0,MTU7C=0;
///////////////MTU3
int value=0;
int PhaseR1=0,PhaseR2=160,PhaseR3=90,PhaseR4=90;
int PhaseL1=0,PhaseL2=0,PhaseL3=90,PhaseL4=90;
int OldPhaseR1=0,OldPhaseR2=0,OldPhaseR3=0,OldPhaseR4=0;
int OldPhaseL1=0,OldPhaseL2=0,OldPhaseL3=0,OldPhaseL4=0;
///////////////SCI
char DataFormKinect[8]={180,20,180,180,0,180,180,180};

//is me

///////////////Game Start

int MTU3_phase2value(int phase){
	if(phase>=160) phase=160;
	value=(int)(phase*210*9.7222222/180)+1000;
	return value;
}

void Delay(int num){
	for (q=0;q<=num;q++);
}

void main(void)
{
	//clock set
	R_PG_Clock_Set();
	//SCI set
	R_PG_SCI_Set_C2();
	//MTU3 set
	R_PG_Timer_Set_MTU_U0_C0();
	R_PG_Timer_Set_MTU_U0_C3();
	R_PG_Timer_Set_MTU_U0_C4();
	R_PG_Timer_Set_MTU_U0_C7();
	R_PG_Timer_SynchronouslyStartCount_MTU_U0(1,1,1,1,1,1,1,1);
	//Initialization
	R_PG_Timer_SetTGR_A_MTU_U0_C0(MTU3_phase2value(PhaseR1));
	R_PG_Timer_SetTGR_C_MTU_U0_C0(MTU3_phase2value(PhaseR2));
	R_PG_Timer_SetTGR_A_MTU_U0_C3(MTU3_phase2value(PhaseR3));
	R_PG_Timer_SetTGR_C_MTU_U0_C3(MTU3_phase2value(PhaseR4));
	R_PG_Timer_SetTGR_A_MTU_U0_C4(MTU3_phase2value(PhaseL1));
	R_PG_Timer_SetTGR_C_MTU_U0_C4(MTU3_phase2value(PhaseL2));
	R_PG_Timer_SetTGR_A_MTU_U0_C7(MTU3_phase2value(PhaseL3));
	R_PG_Timer_SetTGR_C_MTU_U0_C7(MTU3_phase2value(PhaseL4));
	

    R_PG_SCI_StartReceiving_C2(&DataFormKinect[0],8);
	

    while(1){	
		
		PhaseR1=180-DataFormKinect[0];
		PhaseR2=180-DataFormKinect[1];
		PhaseR3=(DataFormKinect[2]-90);
		PhaseR4=(270-DataFormKinect[3]);
		PhaseL1=DataFormKinect[4];
		PhaseL2=180-DataFormKinect[5];
		PhaseL3=(DataFormKinect[6]-90);
		PhaseL4=(270-DataFormKinect[7]);
		
	}

		
}

void Sci2ReFunc(void){
	R_PG_SCI_StartReceiving_C2(&DataFormKinect[0],8);
}

void MTU0_B(void){
	if(OldPhaseR1!=PhaseR1){
		R_PG_Timer_SetTGR_A_MTU_U0_C0(MTU3_phase2value(PhaseR1));
		OldPhaseR1=PhaseR1;
	}
	if(OldPhaseR2!=PhaseR2){
		R_PG_Timer_SetTGR_C_MTU_U0_C0(MTU3_phase2value(PhaseR2));
		OldPhaseR2=PhaseR2;
	}
	if(OldPhaseR3!=PhaseR3){
		R_PG_Timer_SetTGR_A_MTU_U0_C3(MTU3_phase2value(PhaseR3));
		OldPhaseR3=PhaseR3;
	}
	if(OldPhaseR4!=PhaseR4){
		R_PG_Timer_SetTGR_C_MTU_U0_C3(MTU3_phase2value(PhaseR4));
		OldPhaseR4=PhaseR4;
	}
	if(OldPhaseL1!=PhaseL1){
		R_PG_Timer_SetTGR_A_MTU_U0_C4(MTU3_phase2value(PhaseL1));
		OldPhaseL1=PhaseL1;
	}
	if(OldPhaseL2!=PhaseL2){
		R_PG_Timer_SetTGR_C_MTU_U0_C4(MTU3_phase2value(PhaseL2));
		OldPhaseL2=PhaseL2;
	}
	if(OldPhaseL3!=PhaseL3){
		R_PG_Timer_SetTGR_A_MTU_U0_C7(MTU3_phase2value(PhaseL3));
		OldPhaseL3=PhaseL3;
	}
	if(OldPhaseL4!=PhaseL4){
		R_PG_Timer_SetTGR_C_MTU_U0_C7(MTU3_phase2value(PhaseL4));
	    OldPhaseL4=PhaseL4;
	}
	R_PG_Timer_GetRequestFlag_MTU_U0_C0(0,0,0,0,0,0,0,0);
	R_PG_Timer_GetRequestFlag_MTU_U0_C3(0,0,0,0,0,0,0,0);
	R_PG_Timer_GetRequestFlag_MTU_U0_C4(0,0,0,0,0,0,0,0);
	R_PG_Timer_GetRequestFlag_MTU_U0_C7(0,0,0,0,0,0,0,0);
}


#ifdef __cplusplus
void abort(void)
{

}
#endif
